/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.main.ServerEditEvent');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.main.Change');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.main.ServerEditEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.main.ServerEditEvent.repeatedFields_, null);
};
goog.inherits(proto.main.ServerEditEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.main.ServerEditEvent.displayName = 'proto.main.ServerEditEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.main.ServerEditEvent.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.main.ServerEditEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.main.ServerEditEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.main.ServerEditEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.main.ServerEditEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    postsequencenum: jspb.Message.getFieldWithDefault(msg, 1, 0),
    changesList: jspb.Message.toObjectList(msg.getChangesList(),
    proto.main.Change.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.main.ServerEditEvent}
 */
proto.main.ServerEditEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.main.ServerEditEvent;
  return proto.main.ServerEditEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.main.ServerEditEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.main.ServerEditEvent}
 */
proto.main.ServerEditEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPostsequencenum(value);
      break;
    case 2:
      var value = new proto.main.Change;
      reader.readMessage(value,proto.main.Change.deserializeBinaryFromReader);
      msg.addChanges(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.main.ServerEditEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.main.ServerEditEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.main.ServerEditEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.main.ServerEditEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPostsequencenum();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getChangesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.main.Change.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 postSequenceNum = 1;
 * @return {number}
 */
proto.main.ServerEditEvent.prototype.getPostsequencenum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.main.ServerEditEvent.prototype.setPostsequencenum = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated Change changes = 2;
 * @return {!Array.<!proto.main.Change>}
 */
proto.main.ServerEditEvent.prototype.getChangesList = function() {
  return /** @type{!Array.<!proto.main.Change>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.main.Change, 2));
};


/** @param {!Array.<!proto.main.Change>} value */
proto.main.ServerEditEvent.prototype.setChangesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.main.Change=} opt_value
 * @param {number=} opt_index
 * @return {!proto.main.Change}
 */
proto.main.ServerEditEvent.prototype.addChanges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.main.Change, opt_index);
};


proto.main.ServerEditEvent.prototype.clearChangesList = function() {
  this.setChangesList([]);
};


